name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: shyam-medh
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - name: Push to output branch
        run: |
          cd dist
          git init
          git config user.email "baranwal07shyam@gmail.com"
          git config user.name "shyam-medh"
          git checkout -b output
          git add .
          git commit -m "update snake animation"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/shyam-medh/shyam-medh.git" output
